- hosts: "{{ env }}"
  become: yes
  become_user: suresh364
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `docker service ls | grep -v NAME | grep mysvcphp| awk '{print $2}' | grep {{ build }}| wc -l` -gt 0 ]; then  
            docker service rm `docker service ls | grep -v NAME | grep mysvcphp | grep {{ build }}| awk '{print $2}'`
         else 
            echo "No Service found"
         fi
